import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google"; // ❌ отключаем Google Fonts
import "./globals.css";
import { Providers } from "@/components/Providers";
import Header from "@/components/Header";

// Используем CSS-переменные для шрифтов, но сами шрифты подключим через globals.css
const geistSans = {
  variable: "--font-geist-sans",
};

const geistMono = {
  variable: "--font-geist-mono",
};

export const metadata: Metadata = {
  title: "Lady Bake",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <Header />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
